name: Statická analýza

on:
  pull_request:
    branches: [ master ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Informace o prostředí
        run: |
          env

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Composer
        run: |
          composer validate
          composer install

      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse src/ --level 8 --no-progress --error-format github
